screwdriver-cd/scm-base

- index.js
- package.json
- test/index.test.js
This is an initial stab at adding an base implementation for our interactions with source control.
The functions I wrote in this base class come from the different functions that we already call throughout the models. They include:
1.  Getting the commit sha : https://github.com/screwdriver-cd/models/blob/master/lib/buildFactory.js#L51-L56
2. Updating SCM status: https://github.com/screwdriver-cd/models/blob/master/lib/build.js#L22-L32
3. Getting repo permissions: https://github.com/screwdriver-cd/models/blob/master/lib/user.js#L57-L64
These are just what we are calling right now and is definitely not final.
This PR also does not read the schema's from the `screwdriver-data-schema` like it should. I wanted to spike out the initial functions first.
As a discussion, what other functions …
> adding in initial functions that we use in the github helper class

- package.json
The job for data-schema 9.0.2 actually never ran, and the newest version is 10.0.0
> Use the new data-schema

- README.md
- index.js
- test/index.test.js
So that we can expose statistics about our scm usage, this PR adds in a `stats` method to the baseClass so that we can override it in the `scm-github` class
This PR also adds in a README about the interface and how to override functions
> Base Stats Function (merge #1)

- index.js
- package.json
- test/index.test.js
I added `getId` base function for screwdriver-cd/screwdriver#160 .
An actual process will be implemented in scm-github.
> Add a new interface for getRepoId

- README.md
- index.js
- package.json
- test/index.test.js
In preparation for creating a Bitbucket scm plugin, refactoring some functions in the scm base class:
- Add decorators for url, commit, and author
- Add parsers for url and hook
- Deprecate `scmUrl` in favor of `scmUri` (`github.com:12345:master`)
Blocked by https://github.com/screwdriver-cd/data-schema/pull/67
Related to https://github.com/screwdriver-cd/screwdriver/issues/255
> Refactor base scm functions

- index.js
- test/index.test.js
We cannot hit `dataSchema.models.pipeline.base.scmUri` directly
> Needs to do joi.reach for scmUri

- index.js
- test/index.test.js
Since the inner `_parseHook` can throw an error in some cases, the `parseHook` method should catch those. This change is to ensure those errors are caught and a Promise is rejected when `_parseHook` fails.
> Promisify errors from parseHook

- test/index.test.js
This passed in the PR build because https://github.com/screwdriver-cd/screwdriver/issues/285 was not merged yet. Now the master branch build is failing because target url is missing.
> targetUrl was missing in commitstatus

- README.md
- index.js
- test/index.test.js
-  `scm.getFile(`) will either use `scmUri` or `prRef` to get file
Use new data schema from https://github.com/screwdriver-cd/data-schema/pull/78
> Use new getFile validation if PR ref is passed in

- README.md
- index.js
- test/index.test.js
We will change the API instead to pass in ref, not the whole URL. So there is no need for the getFileRef anymore
Should be merged after https://github.com/screwdriver-cd/models/pull/125
> [2] Revert "Use new getFile validation if PR ref is passed in"

- index.js
- package.json
- test/index.test.js
- Use promise for _parseUrl
- Remove validation for resolved results from parseHook
> Use promise for _parseUrl and remove validation

- README.md
- parseHook should return the creator of a webhook event as the `username`
- jobName can optionally be passed into updateCommitStatus (https://github.com/screwdriver-cd/scm-github/blob/master/index.js#L203)
Related to https://github.com/screwdriver-cd/scm-bitbucket/pull/22
> Update username description in README

- CHANGELOG.md
- README.md
- index.js
- package.json
- test/index.test.js
The [launcher](https://github.com/screwdriver-cd/launcher/) is currently hardcoded to checkout repositories from github.com. We want to move that logic into the scm plugins. Adding a method to get checkout commands in the scm-base as an initial step towards that goal.
Relates to https://github.com/screwdriver-cd/screwdriver/issues/312
> Add method to get checkout commands

- README.md
- index.js
- package.json
Use new validation for output of `getCheckoutCommand` method
Blocked by https://github.com/screwdriver-cd/data-schema/pull/94
Related to https://github.com/screwdriver-cd/models/pull/132
> [2] Checkout command name must be sd-checkout-code

- .editorconfig
- README.md
- index.js
- test/index.test.js
Converts `{ pipeline, build }` to a string representing the commands needed to checkout code for a build.
> Add getSetupCommand

- README.md
- index.js
- package.json
- test/index.test.js
Enable a method that adds webhooks to a specific SCM repository. In addition, if the repository already has the desired webhook, it will also refresh/update to ensure it has all the correct information. This is important for a few example scenarios:
* For Github, the webhook API secret changes.
* For Bitbucket & Github, we need to modify which kind of events Screwdriver should react to.
Related to screwdriver-cd/screwdriver#379
> feat(379): Attach webhook to SCM repo

- CHANGELOG.md
- index.js
- package.json
- test/index.test.js
After https://github.com/screwdriver-cd/data-schema/pull/100 is merged, will get `TypeError: Cannot read property 'lookupScmUri' of undefined` because of this bug. 
Related: screwdriver-cd/screwdriver#379
Blocked by: https://github.com/screwdriver-cd/data-schema/pull/100
> fix: actually calls addWebhook function

- README.md
I'm working on the feature discussed on screwdriver-cd/screwdriver#587 (skip builds).
There is a change to a return object of `parseHook`, so I fixed the doc. screwdriver-cd/scm-github#64
> fix(587): Add doc for lastCommitMessage

- .gitignore
- README.md
- index.js
- package.json
- test/index.test.js
This PR adds `getScmContext` and `canHandleUrl` function to scm-base for the multiple scm feature. 
Also, I added these documents and `_getPrInfo` document (it did not exist).
Related: https://github.com/screwdriver-cd/screwdriver/issues/365#issuecomment-313277401
Before merging for test success: https://github.com/screwdriver-cd/data-schema/pull/155
> [DNM] feat(365) - 3: add functions and docs for implementing multiple scm

- README.md
Semantic release failed to determine the version for the last commit, which is a major version bump. Bump version here.
> fix: update README. BREAKING CHANGE: bump version

- index.js
- test/index.test.js
Reject with error object instead of string.
This is giving us problem when we catch the err in the API and try to wrap it with boom.wrap(err). boom.wrap assumes err is an error object.
https://github.com/hapijs/boom#wraperror-statuscode-message
> fix: reject with error

- package.json
Needs this since data-schema is using `13.0.0` and this is breaking `scm-github` pipeline
https://cd.screwdriver.cd/pipelines/8/builds/16574
> fix: update joi

- index.js
- package.json
- screwdriver.yaml
- test/index.test.js
Node.js 6 is slowly becoming deprecated, with popular packages such as `semantic-release` no longer supporting it.
* Change image in `screwdriver.yaml` to `node:8`
* Upgrade `eslint-config-screwdriver` to `^3.0.0`, and lint files
* Minor whitespacing and JSDoc changes, for consistency
> refactor(hip): Upgrade to node:8

- index.js
- package.json
- test/index.test.js
`getCheckoutCommand` needs the parent pipeline model in order to clone its repository.
Pass parent pipeline to `getCheckoutCommand`
Pending:
- https://github.com/screwdriver-cd/data-schema/pull/260
- https://github.com/screwdriver-cd/models/pull/270
https://github.com/screwdriver-cd/screwdriver/issues/1132
> [DNM] feat(1132): Pass parent pipeline to getCheckoutCommand

- README.md
- index.js
Users would like to add custom Git statuses for commits.
This PR adds documentation for `context` and `description` fields to be passed into the `scm.updateCommitStatus` method. The `context` will be the key provided by the user. `description` will be the message they want to show.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1440
> fix(1440): Update documentation for updateCommitStatus [2]

- README.md
- index.js
- package.json
- test/index.test.js
This PR creates the interface of [getCommitRefSha](https://octokit.github.io/rest.js/#api-Repos-getCommitRefSha).
It's used for getting `sha` when `release` and `tag` triggers are fired.
Related Issue: https://github.com/screwdriver-cd/screwdriver/issues/823
Blocked By: https://github.com/screwdriver-cd/data-schema/pull/322
> feat(823): [2] add getCommitRefSha()

- .gitignore
- README.md
- index.js
- test/index.test.js
Would be nice if users could put screwdriver.yaml not at root.
This PR adds `rootDir` as an optional arg to `getCheckoutCommand` and `parseUrl`. Also passes `rootDir` to `getCheckoutCommand` in `getSetupCommand` if it exists.
Related to https://github.com/screwdriver-cd/screwdriver/issues/1455
> fix(1455): Add rootDir to getCheckoutCommand and parseUrl (3.5)

- index.js
**Issue #, if available:** https://github.com/screwdriver-cd/screwdriver/issues/1646
When `pipeline.prSync` is called, it needs base branch info for the PR to get next job for `~pr:<branchName>`.
**Description of changes:**
This PR allow `getPrInfo` to return `baseBranch` value which contains the base branch name of a PR.
This PR is requires below changes before merge.
https://github.com/screwdriver-cd/data-schema/pull/339
I confirm that this contribution is made under the terms of your choice and that I have the authority necessary to make this contribution on behalf of its copyright owner.
> fix(1646): [2] allow getPrInfo to return baseBranch

- index.js
- test/index.test.js
**Issue #, if available:**
**Description of changes:**
There is a bug in chainPR feature.
For PR builds, scm bookend clones build's source code from each SCM, fetches pr refs and merge into the main branch of its pipeline.
But the bookend shouldn't merge the PR branch into the main branch when the build runs under PR specific branch setting because the PR on the SCM will merge into user specified branch not the main branch.
to-be:
* for `~pr` builds
```
$ git clone repo
$ git reset --hard mainBranch
$ git merge prRef
```
* for `~pr:mybranch` builds
```
$ git clone repo
$ git reset --hard mybranch
$ git merge prRef
```
I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary …
> fix: fix base branch for pr specific branch build

- index.js
- test/index.test.js
To use branch info in the event, use baseBranch property instead of commitBranch.
Use baseBranch property instead of commitBranch.
https://github.com/screwdriver-cd/screwdriver/issues/1755
https://github.com/screwdriver-cd/screwdriver/issues/1760
Related PRs:
https://github.com/screwdriver-cd/data-schema/pull/357
https://github.com/screwdriver-cd/models/pull/396
https://github.com/screwdriver-cd/screwdriver/pull/1770
> [3] fix(1755): Use baseBranch

- index.js
- test/index.test.js
I fix issue.
I add new variables,`PR_BRANCH_NAME`
This PR is requires below changes before merge.
https://github.com/screwdriver-cd/data-schema/pull/386
In this PR, get `prBranchName`
> fix(965):[2] $GIT_BRANCH invalid value in PR builds 

- index.js
Chain PR is still broken after GIT_BRANCH fixes.
From OSSD API logs for https://cd.screwdriver.cd/pipelines/2539/pulls
```
200302/193823.384, (1583177902244:sdapi-84f7644d89-tgpmx:19:k7aur1l3:10977) [request,server,error] data: TypeError: Cannot read property 'prBranchName' of undefined
at ScmRouter.getSetupCommand (/usr/src/app/node_modules/screwdriver-scm-base/index.js:185:58)
at /usr/src/app/node_modules/screwdriver-build-bookend/index.js:122:58
at Array.map (<anonymous>)
at Bookend.getSetupCommands (/usr/src/app/node_modules/screwdriver-build-bookend/index.js:122:43)
at /usr/src/app/node_modules/screwdriver-models/lib/buildFactory.js:239:38
at async Promise.all (index 0)
```
Temporarily fix CHAIN_PR. GIT_BRANCH not working can be addressed later.
@kumada626 @ibu1224 …
> fix: hotfix for chainPR not working

- index.js
When PR builds are restarted by API call, prSource information is disappear.
Because of this, restarted PR builds cannot trigger next Jobs.
I added prSource to getPrInfo return value.
screwdriver-cd/screwdriver#2029
> fix(2029): [1] Add prSource to prInfo return value

- index.js
- test/index.test.js
Fixes screwdriver-cd/screwdriver#1079
This PR configures autoDeployKeyGenerationEnabled() to return a non-promise flag
screwdriver-cd/screwdriver#1079
> fix(1079): Fix autoDeployKeyGenerationEnabled to return a non promise flag

- index.js
- package.json
- screwdriver.yaml
Screwdriver hapi.js dependencies are outdated and not supported anymore.
This PR majorly upgrades @hapi/joi version and fixes all schema related changes to be compatible with latest @hapi js dependencies.
https://github.com/screwdriver-cd/screwdriver/issues/1958
> feat(1958): Upgrade joi dependency and dataschema. BREAKING CHANGE: hapi v19

- index.js
Create pipeline is crashing with following error
```(201013/223200.183, (1602628317442:sdapi-beta-6d88b98d8f-89zlr:19:kg8ga5lw:10688) [request,server,error] data: TypeError: Cannot read property 'scmContext' of undefined
at ScmRouter._getWebhookEventsMapping (/usr/src/app/node_modules/screwdriver-scm-router/index.js:163:33)
at ScmRouter.getWebhookEventsMapping (/usr/src/app/node_modules/screwdriver-scm-base/index.js:71:21)
at /usr/src/app/node_modules/screwdriver-models/lib/pipeline.js:408:52
at async handler (/usr/src/app/node_modules/screwdriver-api/plugins/pipelines/create.js:118:13)
at async exports.Manager.execute (/usr/src/app/node_modules/@hapi/hapi/lib/toolkit.js:60:28)
at async Object.internals.handler (/usr/src/app/node_modules/@hapi/hapi/lib/handler.js:46:20)
at async …
```
> fix: pass config properly to getWebhookEventsMapping

- README.md
- index.js
- package.json
- test/index.test.js
We need to get data from the SCM config: read-only flag, scmContext.
This PR:
- adds `getReadOnlyInfo()` method to return read-only SCM config
- adds `getConfig()` method to inject read-only token if read-only enabled
- adds `getScmContext()` method to get `scmContext` based on `hostname`
- adds/fixes tests for `getWebhooksEventsMapping()`
Related to https://github.com/screwdriver-cd/screwdriver/issues/2437
> feat(2437): Add method to get read-only flag [2]

- index.js
- package.json
Would be nice if proper username was used for `decorateAuthor` in event create.
This PR passes in proper headless `username` to `decorateAuthor` when read-only SCM enabled.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2437, #87 
> fix(2437): Pass in headless user for decorateAuthor [1]

- index.js
- package.json
Modify the API documentation to follow the changes at https://github.com/screwdriver-cd/scm-github/pull/200.
- Change the name of the argument in API documentation of `getChangedFiles`
[data-schema PR](https://github.com/screwdriver-cd/data-schema/pull/471)
[scm-github PR](https://github.com/screwdriver-cd/scm-github/pull/200)
[scm-gitlab PR](https://github.com/screwdriver-cd/scm-gitlab/pull/49)
[screwdriver PR](https://github.com/screwdriver-cd/screwdriver/pull/2622)
https://github.com/screwdriver-cd/screwdriver/issues/1769#issuecomment-934107626
> feat(1769): [2] Change data structure for queue-service cooperation.

- package.json
- test/index.test.js
getChangedFiles test is failing after new data-schema changes (https://github.com/screwdriver-cd/data-schema/pull/471).
Also semantic release will fail.
This PR fixes getChangedFiles test and verifyConditions for semantic release.
Related to https://github.com/screwdriver-cd/scm-base/pull/90
> fix: semantic release by removing verifyConditions

- index.js
- test/index.test.js
Cannot start build if rootDirectory contains a colon.
I fix to correctly parse rootDirectory even if it contains a colon.
issue: https://github.com/screwdriver-cd/screwdriver/issues/2952
PR:
- https://github.com/screwdriver-cd/scm-github/pull/220
- https://github.com/screwdriver-cd/launcher/pull/469
- https://github.com/screwdriver-cd/data-schema/pull/544
> fix(2952): Allow colon to be used in root directory

- index.js
- package.json
- test/index.test.js
`decorateAuthor()` could throw an error when the user profile does not exist in the scm for the specified login.
This error bubbles up to the caller and breaks certain workflows.
Ex:
Event creation failed when there is a failure to get user info from the scm.
All of these additional info are optional and mostly used for display purpose in the UI.
Do not bubble up the error to the caller. Instead set default values for these optional fields.
https://github.com/screwdriver-cd/screwdriver/issues/3384
> fix(3384): Failure to get user info from scm should not throw error
