screwdriver-cd/scm-base

index.js
package.json

Updating to the latest deps and docs
Blocked by https://github.com/screwdriver-cd/data-schema/pull/55

[2] Updating dependencies

---

README.md
index.js

parseHook returns a Promise, _parseHook does not

---

package.json

Trying to see if this will help with https://github.com/screwdriver-cd/screwdriver/issues/274
Merged after https://github.com/screwdriver-cd/data-schema/pull/74 is done publishing

Update joi version

---

index.js
test/index.test.js

- Target url is required because of https://github.com/screwdriver-cd/data-schema/pull/77
- Remove data schema mock so it can actually tests against it
- Relates to https://github.com/screwdriver-cd/screwdriver/issues/285

Target url is required, Remove schema mock

---

README.md
index.js
package.json
test/index.test.js

This will allow different SCM systems to configure bell appropriately.

Exposing a Bell authentication configuration method

---

README.md

- parseHook() should return hook event uuid

Add hookId to parseHook

---

package.json

- Pull in the v15 data-schema
- Bump minor version to make sure scm-bitbucket and scm-github pull in the right one

[6]Pull in v15 data-schema

---

package.json
test/index.test.js

also made the spacing consistent

remove mockery

---

package.json

- Update joi to version 10.0.5.
- Need to be merged before scm-github and scm-bitbucket

[1] Update joi to version 10.0.5

---

README.md

Use new pipeline id for the badge

fix: Update Screwdriver pipeline badge link

---

README.md
index.js
package.json
test/index.test.js

Add getOpenedPRs to required methods
Related: https://github.com/screwdriver-cd/screwdriver/issues/417

feat: Add getOpenedPRs to required methods

---

index.js
test/index.test.js

feat: add  a`getPrInfo` function
related to https://github.com/screwdriver-cd/screwdriver/issues/244

feat: add getPrInfo function

---

package-lock.json
package.json
screwdriver.yaml

Node 8 was released on May 30th! https://nodejs.org/en/blog/release/v8.0.0/
Use Node 8 to build `scm-base`
* https://nodejs.org/en/blog/release/v8.0.0/

chore: use node8 for building

---

README.md
package.json

https://github.com/screwdriver-cd/data-schema/pull/216

fix: Pull in latest data-schema change

---

index.js
package.json

Related to https://github.com/screwdriver-cd/data-schema/pull/218

fix(911): Pull in the new data-schema

---

README.md
index.js

Adding functions to decorate new pr field in events
Related to https://github.com/screwdriver-cd/screwdriver/issues/822

decorate pr

---

README.md
index.js
lib/helper.js
test/index.test.js

Pending merge of https://github.com/screwdriver-cd/data-schema/pull/236
https://github.com/screwdriver-cd/screwdriver/issues/1041

[1] feat(1041): Pass manifest to checkoutConfig

---

README.md
index.js
test/index.test.js

To get pipelines, we need a function which get list of branch.  
Add getBranchList function which will return branch list.
Blocked by https://github.com/screwdriver-cd/data-schema/pull/240
Related to screwdriver-cd/screwdriver#1082

feat(1082): [2] add get branch list function

---

index.js

Refactoring the place of branchList to same place of other scm repositories. 
Also add jsdoc of scmContext
- Change branchList place.
- fix jsdoc
Related to screwdriver-cd/screwdriver#1082

fix(1082): [3] refact and add comment to branchList

---

index.js
test/index.test.js

When specific branch jobs are triggered, we have to clone from the branch.
Set commitBranch, if there is commitBranch.
Related to screwdriver-cd/screwdriver#1082

feat(1082): [8] set commit branch

---

README.md
index.js
package-lock.json
test/index.test.js

- add a function to check user's permission on an smc organization
Blocked by: https://github.com/screwdriver-cd/data-schema/pull/291

fix(1319): add getOrgPermissions function

---

package.json

upgrade jenkins-mocha for a security vulnerability

fix: upgrade jenkins-mocha

---

index.js
package.json
test/index.test.js

related: https://github.com/screwdriver-cd/screwdriver/issues/1419
related: https://github.com/screwdriver-cd/ui/pull/395
blocked by: https://github.com/screwdriver-cd/data-schema/pull/309

fix: more pr & author info

---

index.js

Because of https://github.com/screwdriver-cd/scm-github/pull/145
- Add `mergeable` attribute to return value
https://github.com/screwdriver-cd/screwdriver/issues/1468

fix(1468): [1] Add mergeable

---

README.md
index.js
package.json
test/index.test.js

Sd onboarding feature requires an api to open pull request 
Add a method `openPr` for opening pull request to support sd onboarding feature
https://github.com/screwdriver-cd/screwdriver/issues/1922

feat(1922): Add openPr method. BREAKING CHANGE: New method is required

---

README.md
index.js
test/index.test.js

Fixes screwdriver-cd/screwdriver#1079
Refer #screwdriver-cd/scm-github#163
Fixes screwdriver-cd/screwdriver#1079

feat(1079): Add methods for deploy key generation pipeline [3]

---

index.js
test/index.test.js

screwdriver-cd/screwdriver#1415
screwdriver-cd/screwdriver#1415

feat(1415): Add mapping of scm actions with tests

---

index.js
package.json
test/index.test.js

change the validation to support multiple pr comments 
https://github.com/screwdriver-cd/screwdriver/issues/2873

feat(2873): allow user to split pr comments

---

README.md
index.js
test/index.test.js

Add isEnterpriseUser fn to base
This PR adds isEnterpriseUser fn to base
https://github.com/screwdriver-cd/scm-github/pull/224

feat: add fn to scm-base
